spring:
  application:
    name: data_works
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      base-path: /actuator
    enabled-by-default: true
server:
  port: 10001
flink:
  sql-client: /Users/cqx/Projects/flink-learning/flink-1.14.6/bin/sql-client.sh