package com.statestreet.data_works.model.dto.sqljob;

import com.statestreet.data_works.model.dto.BaseDTO;
import com.statestreet.data_works.model.dto.CreateDTO;
import lombok.Data;

@Data
public class SqlJobCreateDTO extends CreateDTO {

    private String content = "CREATE TABLE products (\n" + "    id INT,\n" + "    name STRING,\n" + "    description STRING,\n" + "    PRIMARY KEY (id) NOT ENFORCED\n" + "  ) WITH (\n" + "    'connector' = 'mysql-cdc',\n" + "    'hostname' = 'localhost',\n" + "    'port' = '3306',\n" + "    'username' = 'root',\n" + "    'password' = '123456',\n" + "    'database-name' = 'mydb',\n" + "    'table-name' = 'products'\n" + "  );\n" + "  CREATE TABLE orders (\n" + "   order_id INT,\n" + "   order_date TIMESTAMP(0),\n" + "   customer_name STRING,\n" + "   price DECIMAL(10, 5),\n" + "   product_id INT,\n" + "   order_status BOOLEAN,\n" + "   PRIMARY KEY (order_id) NOT ENFORCED\n" + " ) WITH (\n" + "   'connector' = 'mysql-cdc',\n" + "   'hostname' = 'localhost',\n" + "   'port' = '3306',\n" + "   'username' = 'root',\n" + "   'password' = '123456',\n" + "   'database-name' = 'mydb',\n" + "   'table-name' = 'orders'\n" + " );\n" + "CREATE TABLE shipments (\n" + "   shipment_id INT,\n" + "   order_id INT,\n" + "   origin STRING,\n" + "   destination STRING,\n" + "   is_arrived BOOLEAN,\n" + "   PRIMARY KEY (shipment_id) NOT ENFORCED\n" + " ) WITH (\n" + "   'connector' = 'postgres-cdc',\n" + "   'hostname' = 'localhost',\n" + "   'port' = '5432',\n" + "   'username' = 'postgres',\n" + "   'password' = 'postgres',\n" + "   'database-name' = 'postgres',\n" + "   'schema-name' = 'public',\n" + "   'table-name' = 'shipments'\n" + " );\n" + " CREATE TABLE enriched_orders (\n" + "   order_id INT,\n" + "   order_date TIMESTAMP(0),\n" + "   customer_name STRING,\n" + "   price DECIMAL(10, 5),\n" + "   product_id INT,\n" + "   order_status BOOLEAN,\n" + "   product_name STRING,\n" + "   product_description STRING,\n" + "   shipment_id INT,\n" + "   origin STRING,\n" + "   destination STRING,\n" + "   is_arrived BOOLEAN,\n" + "   PRIMARY KEY (order_id) NOT ENFORCED\n" + " ) WITH (\n" + "     'connector' = 'elasticsearch-7',\n" + "     'hosts' = 'http://localhost:9200',\n" + "     'index' = 'enriched_orders'\n" + " );\n" + " INSERT INTO enriched_orders\n" + " SELECT o.*, p.name, p.description, s.shipment_id, s.origin, s.destination, s.is_arrived\n" + " FROM orders AS o\n" + " LEFT JOIN products AS p ON o.product_id = p.id\n" + " LEFT JOIN shipments AS s ON o.order_id = s.order_id;";

}
